### ISSUE TITLE
Linking to criticism

### ISSUE THREAD

**Issue by henryaj** [sheonhan/awesome-effective-altruism#1]
Do you think there's scope to link to well-known criticisms of EA, in the spirit of completeness?

Most EA critiques are hopeless, but there are a few cogent ones that I know I'd have wanted to know about if I was coming to the topic for the first time.

**Comment by henryaj** [comment]
(Love what you've done here, btw.)

**Comment by sheonhan** [comment]
@henryaj I apologize for this long overdue comment. `awesome-effective-altruism` was added to the official `awesome` repositories just this morning 🎉  

I added a "Criticism & Critique" section and put a few articles that I've found to be good reads in the past. 

Feel free to make pull requests!
